H02_topics:
  # - {
  #     topic: "/H02/cam_back/image_rect_color",
  #     expected_hz: 15.0
  #   }
  
  # - {
  #     topic: "/H02/cam_front/image_rect_color",
  #     expected_hz: 15.0
  #   }

  # - {
  #     topic: "/H02/cam_left/image_rect_color",
  #     expected_hz: 15.0
  #   }

  # - {
  #     topic: "/H02/cam_right/image_rect_color",
  #     expected_hz: 15.0
  #   }

  - {
      topic: "/H02/imu/data",
      expected_hz: 500.0
    }

  - {
      topic: "/H02/horiz/os_cloud_node/points",
      expected_hz: 20.0
    }

  - {
      topic: "/H02/vert/os_cloud_node/points",
      expected_hz: 20.0
    }

  - {
      topic: "/H02/scan",
      expected_hz: 10.0 
    }

  # - {
  #     topic: "/H02/pico_flexx_left/points",
  #     expected_hz: 
  #   }

  # - {
  #     topic: "/H02/pico_flexx_right/points",
  #     expected_hz: 
  #   }

  # - {
  #     topic: "/H02/lio_sam/mapping/odometry",
  #     expected_hz: 
  #   }

  # - {
  #     topic: "/H02/merged_map",
  #     expected_hz: 
  #   }

  # - {
  #     topic: "/H02/octomap_in",
  #     expected_hz: 
  #   }

  # - {
  #     topic: "/H02/scan_plan_node/path_out",
  #     expected_hz: 
  #   }
